// <auto-generated />
using System;
using ClientHealthWebserviceV3.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClientHealthWebServiceV3.Migrations
{
    [DbContext(typeof(ClientDBContext))]
    partial class ClientDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClientHealthWebserviceV3.Models.Client", b =>
                {
                    b.Property<string>("ClientHealthId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("AdminShare")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Architecture")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("BITS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Build")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CacheSize")
                        .HasColumnType("int");

                    b.Property<string>("ClientCertificate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ClientInstalled")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClientInstalledReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DNS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Domain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Drivers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Extension_000")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Extension_001")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Extension_002")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Extension_003")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Extension_004")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Extension_005")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Extension_006")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Extension_007")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Extension_008")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Extension_009")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Extension_010")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Extension_011")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Extension_012")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Extension_013")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Extension_014")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Extension_015")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Extension_016")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Extension_017")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Extension_018")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Extension_019")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("HWInventory")
                        .HasColumnType("datetime2");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InstallDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastBootTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastLoggedOnUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaxLogHistory")
                        .HasColumnType("int");

                    b.Property<int?>("MaxLogSize")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("OSDiskFreeSpace")
                        .HasColumnType("float");

                    b.Property<DateTime?>("OSUpdates")
                        .HasColumnType("datetime2");

                    b.Property<string>("OperatingSystem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PSBuild")
                        .HasColumnType("int");

                    b.Property<double?>("PSVersion")
                        .HasColumnType("float");

                    b.Property<int?>("PatchLevel")
                        .HasColumnType("int");

                    b.Property<string>("PendingReboot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProvisioningMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshComplianceState")
                        .HasColumnType("datetime2");

                    b.Property<string>("SWMetering")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Services")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sitecode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("StateMessages")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Updates")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Version")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("WMI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WUAHandler")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientHealthId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("ClientHealthWebserviceV3.Models.ClientConfiguration", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ClientConfiguration");
                });
#pragma warning restore 612, 618
        }
    }
}
